# -*- coding: utf-8 -*-
"""Another copy of Financial Data Analysis using Python (Microsoft, Apple, Tesla).py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5T2e8vxbdxy-iZbaCfrhiWwek3gVeQ7

#**Financial Trend Analysis (2022–2024)**

This project analyzes financial data from Microsoft, Apple, and Tesla over three years.

The goal is to identify growth trends in revenue and profitability, and generate insights that could support decision-making in an AI-powered financial system.
"""



import pandas as pd

data = {
    "Company": ["Microsoft","Microsoft","Microsoft","Apple","Apple","Apple","Tesla","Tesla","Tesla"],
    "Year": [2022,2023,2024,2022,2023,2024,2022,2023,2024],
    "Revenue": [198270,211915,245122,394328,383285,391035,81462,96773,96773],
    "Net Income": [72738,72361,88136,99803,96995,93736,12587,14997,15000]
}

df = pd.DataFrame(data)

df["Revenue Growth %"] = df.groupby("Company")["Revenue"].pct_change()*100
df["Net Income Growth %"] = df.groupby("Company")["Net Income"].pct_change()*100

df

import matplotlib.pyplot as plt

for company in df["Company"].unique():
    subset = df[df["Company"] == company]
    plt.plot(subset["Year"], subset["Revenue"], label=company)

plt.title("Revenue Trend (2022–2024)")
plt.xlabel("Year")
plt.ylabel("Revenue")
plt.legend()
plt.show()

"""# Key Insights

- Microsoft shows strong and accelerating growth, especially in 2024.
- Apple remains stable but shows slight decline in profitability.
- Tesla experienced rapid growth followed by stabilization.
- Different companies are at different growth stages, which is critical for investment or strategic decisions.

#Analysis Summary:

Microsoft shows strong and accelerating growth in both revenue and net income, indicating expanding business performance. Apple remains relatively stable, though slight declines in revenue and profit suggest slowing momentum. Tesla demonstrates rapid growth from 2022 to 2023, followed by stabilization in 2024.

Overall, the data highlights different growth stages across companies, with Microsoft leading in consistent expansion, Apple maintaining maturity, and Tesla transitioning from high growth to steady performance.

# Conclusion

This analysis demonstrates how financial data can be transformed into actionable insights using Python. Such workflows can support AI-driven financial tools in identifying trends, risks, and growth opportunities.
"""